source 'https://rubygems.org'

gem 'jekyll', '~> 4.2.0'
gem 'jekyll-archives'
gem 'jekyll-diagrams'
gem 'jekyll-email-protect'
gem 'jekyll-feed', '~> 0.12'
gem 'jekyll-github-metadata'
gem 'jekyll-imagemagick'
gem 'jekyll-paginate-v2'
gem 'jekyll-scholar'
gem 'jekyll-seo-tag', '~> 2.6'
gem 'jekyll-sitemap'
gem 'jekyll-target-blank'
gem 'jekyll-twitter-plugin'
gem 'jemoji'
gem 'unicode_utils'
gem 'webrick'